docs: updates to support.md
deneb-viz/deneb-viz.github.io pull request #39
Opened 2024-01-05 01:42 UTC by Giammaria

Updates included per discussion. Please don't hesitate to provide feedback, make changes, request changes.

2024-01-05 01:46 UTC, Giammaria commented
@dm-p, @pbi-david, I don't see the option to request reviewers, so tagging you all here

2024-01-05 08:45 UTC, PBI-David commented
Looks perfect to me - nothing to add but my thanks.

2024-01-06 06:07 UTC, dm-p requested changes
@Giammaria: thank you so much for doing this. It's an excellent replacement for what was there previously 💪

I do have a few suggestions for improving the messaging a little bit, as well as a couple of functional issues with links etc. but hopefully these are minor changes. If you make any subsequent commits and pushes, it should update the PR and I can do another skim over it.

2024-01-06 06:07 UTC, dm-p commented on src/pages/support.md
> +:::info NOTE
Thanks for turning this section into an admonition. Can you please amend the title here to _Before you consider creating a GitHub issue..._ rather than _NOTE_? 

(I'm aware that Docusaurus will capitalize the above title, so feel free to type it however you like; I usually type them in normal sentence case, but whatevs)

2024-01-06 17:00 UTC, Giammaria commented on src/pages/support.md
> +Open an [issue in the documentation repository](https://github.åç/deneb-viz/deneb-viz.github.io/issues) and include:
No idea how this happened, but addressed 😅

2024-01-06 17:04 UTC, Giammaria commented
@dm-p, I appreciate the valuable feedback and recommendations. I believe I have addressed everything. Take a look when you have time. I'm happy to repeat this feedback-commit cycle as many times as necessary. 🚀

2024-01-07 04:47 UTC, dm-p approved these changes
Thanks, @Giammaria - looks great! I will hopefully merge and publish soon and will put out a post about the changes when they're deployed 👍

2024-01-11 21:00 UTC, merged